import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart' show Clipboard, ClipboardData;
import 'package:provider/provider.dart';

import '../controllers/app_controller.dart';
import '../models/location.dart';
import '../services/api_client.dart';
import '../services/rfid_service.dart';
import '../theme.dart';
import '../widgets/common.dart';

enum _Step { create, label, rfid, putaway, success }

enum _LocInputMode { scan, manual }

/// One distinct tag the RFID sweep turned up — same shape/reasoning as
/// RfidRegisterScreen's own _Candidate.
class _Candidate {
  final String epc;
  final int? rssi;
  final int hits;
  const _Candidate({required this.epc, this.rssi, required this.hits});
}

/// Receiving flow, start to finish: create the box row the moment it comes
/// off a supplier truck, confirm the barcode sticker's actually on it,
/// optionally commission an RFID tag, then put it away on an actual shelf.
/// Copied step-for-step from legacy.html's own box-registration handler
/// ($('#btnAddBox').onclick) and putaway modal — same lifecycle
/// (pending/unlabeled -> labeled -> warehouse), same history entries
/// (dir: reg/label/putaway), just one box at a time instead of the web's
/// desktop-only bulk-prefix generator.
class BoxRegisterScreen extends StatefulWidget {
  const BoxRegisterScreen({super.key});
  @override
  State<BoxRegisterScreen> createState() => _BoxRegisterScreenState();
}

class _BoxRegisterScreenState extends State<BoxRegisterScreen> {
  final _tagCtrl = TextEditingController();
  final _tagFocus = FocusNode();

  // Lot code and expiry date — both optional, both scan-or-type. Neither
  // auto-submits the box (unlike _tagCtrl's burst detection above): a
  // supplier's lot/expiry barcode landing here mid-typing-the-box-code
  // would be exactly the wrong field to treat as "the box is confirmed
  // now", so these just sit in the form until the operator's own barcode
  // scan/Enter on _tagCtrl actually creates the box.
  final _lotCtrl = TextEditingController();
  final _expiryCtrl = TextEditingController();

  // Putaway location — cascading Zone/Rack/Shelf/Slot picked from the
  // Location Master, or filled in one shot by scanning a rack barcode.
  // Same two-mode pattern as legacy.html's locPickerHtml().
  _LocInputMode _locMode = _LocInputMode.scan;
  final _rackScanCtrl = TextEditingController();
  final _rackScanFocus = FocusNode();
  String? _locZone;
  String? _locRack;
  String? _locShelf;
  String? _locSlot;
  String? _locScanError;
  bool _locConfirmed = false;

  Timer? _autoSubmitTimer;
  static const _autoSubmitDelay = Duration(milliseconds: 180);
  static const _autoSubmitMinLen = 2;
  // A hardware barcode scanner types its whole payload as a keyboard-wedge
  // burst — every character lands within a few ms of the last. A human
  // thumbing this in on the handheld's own keypad is nowhere near that fast
  // even typing quickly. Tracking the gap between keystrokes (not just "did
  // the field go quiet") is what actually tells the two apart — length/quiet
  // alone auto-submitted a name someone was still typing the instant they
  // paused. `null` means "no burst seen yet this field session".
  static const _burstMaxGap = Duration(milliseconds: 40);
  DateTime? _lastKeyAt;
  bool _sawBurst = false;

  // Route guard: this whole flow (create/label/rfid/putaway) writes straight
  // to the server step by step with no offline queue behind it — losing the
  // connection mid-flow has to bail out immediately, not fail silently on
  // whichever button gets tapped next. Latched so the toast+redirect fires
  // once per drop, not on every rebuild while already on the way out.
  bool _leftForOffline = false;

  _Step _step = _Step.create;
  String? _selectedType;
  String? _tag; // confirmed once created
  String? _error;
  bool _creating = false;
  bool _labeling = false;
  bool _puttingAway = false;

  // Auto-generated by default (see _nextTagForType/_genTagId, ported from
  // legacy.html's own nextTagForType/genTagId) — "แก้เอง" lets an operator
  // override with a barcode they're scanning/typing instead, matching the
  // legacy web form's own auto-tag-row pattern exactly.
  bool _tagOverride = false;
  String? _typeError; // set only after a failed submit attempt — see _validateCreate
  String? _tagError;

  // Label step: the barcode the operator actually scans off the sticker they
  // just applied has to match _tag, or the sticker's on the wrong box (or
  // this one's smudged/misread) — see _onLabelScan.
  final _labelScanCtrl = TextEditingController();
  final _labelScanFocus = FocusNode();
  String? _labelScanError;

  // RFID sweep — identical mechanics to RfidRegisterScreen.
  StreamSubscription<RfidTagRead>? _tagSub;
  StreamSubscription<RfidStatus>? _statusSub;
  RfidStatus _rfidStatus = const RfidStatus(RfidState.idle, '');
  final List<_Candidate> _found = [];
  String? _selectedEpc;
  bool _binding = false;
  String? _rfidError;
  RfidService? _rfid;
  Timer? _successTimer;

  AppController get _c => context.read<AppController>();

  @override
  void initState() {
    super.initState();
    final rfid = _c.rfid;
    _rfid = rfid;
    _rfidStatus = RfidStatus(rfid.state, '');
    _statusSub = rfid.status.listen((s) => setState(() => _rfidStatus = s));
    _tagSub = rfid.tagReads.listen(_onTagRead);
    if (rfid.supported && rfid.state != RfidState.connected) rfid.connect();
    _tagCtrl.addListener(_onTagChanged);
    _tagCtrl.text = _nextTagForType(null);
    _labelScanCtrl.addListener(_onLabelScanChanged);
    WidgetsBinding.instance.addPostFrameCallback((_) => _tagFocus.requestFocus());
  }

  @override
  void dispose() {
    _rfid?.stopInventory();
    _tagSub?.cancel();
    _statusSub?.cancel();
    _successTimer?.cancel();
    _autoSubmitTimer?.cancel();
    _tagCtrl.removeListener(_onTagChanged);
    _tagCtrl.dispose();
    _labelAutoTimer?.cancel();
    _labelScanCtrl.removeListener(_onLabelScanChanged);
    _labelScanCtrl.dispose();
    _labelScanFocus.dispose();
    _tagFocus.dispose();
    _lotCtrl.dispose();
    _expiryCtrl.dispose();
    _rackScanCtrl.dispose();
    _rackScanFocus.dispose();
    super.dispose();
  }

  static const _genTagChars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  final _tagRnd = Random();

  /// Fallback when no box type is picked yet — 'BTX-YYYYMMDD-XXXXX', retried
  /// against the cached box list until it isn't already taken. Ported
  /// 1:1 from legacy.html's own genTagId().
  String _genTagId() {
    final d = DateTime.now();
    final ds = '${d.year}${d.month.toString().padLeft(2, '0')}${d.day.toString().padLeft(2, '0')}';
    final existing = _c.S?.boxesRaw.keys.toSet() ?? const <String>{};
    for (var attempt = 0; attempt < 100; attempt++) {
      final r = String.fromCharCodes(
          List.generate(5, (_) => _genTagChars.codeUnitAt(_tagRnd.nextInt(_genTagChars.length))));
      final tag = 'BTX-$ds-$r';
      if (!existing.contains(tag)) return tag;
    }
    // Exhausted retries (100 collisions in a row is practically impossible,
    // but a tag has to come back regardless) — one more roll, accept it.
    final r = String.fromCharCodes(
        List.generate(5, (_) => _genTagChars.codeUnitAt(_tagRnd.nextInt(_genTagChars.length))));
    return 'BTX-$ds-$r';
  }

  /// legacy.html's tagPrefixForType — the type id, upper-cased and stripped
  /// to A-Z0-9, plus a trailing dash.
  String _tagPrefixForType(String typeId) => '${typeId.toUpperCase().replaceAll(RegExp(r'[^A-Z0-9]'), '')}-';

  /// legacy.html's nextTagForType — same running counter per type prefix, so
  /// a box registered here and one added from the web's own bulk-prefix
  /// generator continue the exact same sequence instead of two independent
  /// numbering schemes colliding later.
  String _nextTagForType(String? typeId) {
    if (typeId == null || typeId.isEmpty) return _genTagId();
    final prefix = _tagPrefixForType(typeId);
    var max = 0;
    for (final id in _c.S?.boxesRaw.keys ?? const <String>[]) {
      if (!id.startsWith(prefix)) continue;
      final n = int.tryParse(id.substring(prefix.length));
      if (n != null && n > max) max = n;
    }
    return '$prefix${max + 1}';
  }

  /// "สร้างรหัสใหม่" — only meaningful in auto mode; a manually-typed/scanned
  /// override has nothing to regenerate. Shows the locally-computed guess
  /// instantly (no flash of an empty field), then corrects it against the
  /// server's live count once that answers — this device's own boxesRaw
  /// cache can be stale if another device just registered a box under the
  /// same type prefix since this one last synced.
  bool _fetchingNextTag = false;
  void _regenerateTag() {
    if (_tagOverride) return;
    final type = _selectedType;
    setState(() {
      _tagCtrl.text = _nextTagForType(type);
      _tagError = null;
    });
    if (type == null || type.isEmpty || _fetchingNextTag) return;
    _fetchingNextTag = true;
    _c.api.nextBoxTag(type).then((tag) {
      _fetchingNextTag = false;
      if (!mounted || tag == null || _tagOverride || _selectedType != type) return;
      setState(() => _tagCtrl.text = tag);
    });
  }

  /// "แก้เอง" / "อัตโนมัติ" toggle. Switching back to auto immediately
  /// regenerates — leaving a manually-typed value sitting in an "auto" field
  /// would otherwise look auto-generated when it wasn't.
  void _toggleTagOverride() {
    setState(() {
      _tagOverride = !_tagOverride;
      _tagError = null;
    });
    if (_tagOverride) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _tagFocus.requestFocus());
    } else {
      _regenerateTag();
    }
  }

  Widget _iconBtn(IconData icon, String tooltip, VoidCallback onTap) {
    return Material(
      color: C.neutralBg,
      borderRadius: BorderRadius.circular(11),
      child: InkWell(
        borderRadius: BorderRadius.circular(11),
        onTap: onTap,
        child: Tooltip(
          message: tooltip,
          child: SizedBox(width: 44, height: 44, child: Icon(icon, size: 19, color: C.ink2)),
        ),
      ),
    );
  }

  void _onTagChanged() {
    _autoSubmitTimer?.cancel();
    if (!_tagOverride) return; // auto mode never self-edits into a submit
    final now = DateTime.now();
    final prev = _lastKeyAt;
    _lastKeyAt = now;
    // Any single keystroke that lands within the burst window counts —
    // that's already proof this edit wasn't a person tapping keys, so one
    // fast gap is enough to arm auto-submit for the rest of this value.
    if (prev != null && now.difference(prev) <= _burstMaxGap) _sawBurst = true;

    final text = _tagCtrl.text.trim();
    if (!_sawBurst || text.length < _autoSubmitMinLen || _creating || _selectedType == null) return;
    _autoSubmitTimer = Timer(_autoSubmitDelay, () {
      if (!mounted || _creating || _tagCtrl.text.trim() != text) return;
      _submitCreate();
    });
  }

  /// Per-field red-border validation instead of one generic banner —
  /// _typeError/_tagError are only ever set here (a failed submit attempt),
  /// never eagerly while the operator is still filling the form in, so a
  /// blank required field doesn't turn red before they've had a chance to
  /// touch it.
  bool _validateCreate() {
    final tag = _tagCtrl.text.trim();
    setState(() {
      _typeError = _selectedType == null ? 'เลือกประเภทกล่องก่อน' : null;
      _tagError = tag.isEmpty ? 'ยิงหรือพิมพ์บาร์โค้ดกล่อง' : null;
    });
    return _typeError == null && _tagError == null;
  }

  Future<void> _submitCreate() async {
    if (!_validateCreate()) return;
    final tag = _tagCtrl.text.trim();
    final type = _selectedType!;
    _autoSubmitTimer?.cancel();
    setState(() {
      _creating = true;
      _error = null;
    });
    try {
      final box = await _c.api.createBox(
        tag,
        type: type,
        lot: _lotCtrl.text.trim(),
        expiry: _expiryCtrl.text.trim(),
      );
      setState(() {
        _tag = box['tag'] as String? ?? tag.toUpperCase();
        _step = _Step.label;
      });
      WidgetsBinding.instance.addPostFrameCallback((_) => _labelScanFocus.requestFocus());
      _lotCtrl.clear();
      _expiryCtrl.clear();
    } on ApiException catch (e) {
      // 'tag_taken' is a validation-shaped rejection (this exact barcode
      // already belongs to another box) — surfaces on the tag field itself,
      // same red-border treatment as an empty field, rather than a generic
      // banner the operator has to go find the cause of.
      if (e.code == 'tag_taken') {
        setState(() => _tagError = e.message);
      } else {
        setState(() => _error = e.message);
      }
    } catch (e) {
      setState(() => _error = 'สร้างกล่องไม่สำเร็จ');
    } finally {
      if (mounted) setState(() => _creating = false);
    }
  }

  Timer? _labelAutoTimer;
  DateTime? _labelLastKeyAt;
  bool _labelSawBurst = false;

  void _onLabelScanChanged() {
    _labelAutoTimer?.cancel();
    final now = DateTime.now();
    final prev = _labelLastKeyAt;
    _labelLastKeyAt = now;
    if (prev != null && now.difference(prev) <= _burstMaxGap) _labelSawBurst = true;
    final text = _labelScanCtrl.text.trim();
    if (!_labelSawBurst || text.length < _autoSubmitMinLen || _labeling) return;
    _labelAutoTimer = Timer(_autoSubmitDelay, () {
      if (!mounted || _labeling || _labelScanCtrl.text.trim() != text) return;
      _submitLabelScan();
    });
  }

  /// The operator scans the sticker they just physically applied — not a
  /// "trust me, I did it" button. Whatever they scan has to actually equal
  /// this box's own tag, or the sticker is on the wrong box (or this one's
  /// misread/smudged); either way, "ติดป้ายแล้ว" isn't true yet and the API
  /// call that records it never fires until it is.
  Future<void> _submitLabelScan() async {
    final tag = _tag;
    if (tag == null || _labeling) return;
    final scanned = _labelScanCtrl.text.trim();
    if (scanned.isEmpty) return;
    _labelAutoTimer?.cancel();
    if (scanned.toUpperCase() != tag.toUpperCase()) {
      setState(() => _labelScanError = 'บาร์โค้ดที่ยิงไม่ตรงกับรหัสกล่อง $tag — ยิงผิดกล่องหรือสติกเกอร์ยังไม่ตรง ลองยิงใหม่');
      _labelScanCtrl.clear();
      _labelLastKeyAt = null;
      _labelSawBurst = false;
      return;
    }
    setState(() {
      _labeling = true;
      _error = null;
      _labelScanError = null;
    });
    try {
      await _c.api.labelBox(tag);
      setState(() => _step = _Step.rfid);
      // Same reasoning as RfidRegisterScreen: arm the reader the instant
      // this step opens rather than making the operator tap something
      // first — they're already holding the gun on this exact box.
      unawaited(_c.rfid.startInventory());
    } catch (e) {
      setState(() => _error = e is ApiException ? e.message : 'ยืนยันติดป้ายไม่สำเร็จ');
    } finally {
      if (mounted) setState(() => _labeling = false);
    }
    _labelScanCtrl.clear();
    _labelLastKeyAt = null;
    _labelSawBurst = false;
  }

  void _onTagRead(RfidTagRead read) {
    if (_step != _Step.rfid || _binding) return;
    if (read.epc.isEmpty) return;
    setState(() {
      final existing = _found.indexWhere((c) => c.epc == read.epc);
      if (existing >= 0) {
        final c = _found[existing];
        _found[existing] = _Candidate(
          epc: c.epc,
          rssi: (read.rssi ?? -999) > (c.rssi ?? -999) ? read.rssi : c.rssi,
          hits: c.hits + 1,
        );
      } else {
        _found.insert(0, _Candidate(epc: read.epc, rssi: read.rssi, hits: 1));
      }
      _rfidError = null;
    });
  }

  Future<void> _bindSelected() async {
    final tag = _tag;
    final epc = _selectedEpc;
    if (tag == null || epc == null || _binding) return;
    setState(() {
      _binding = true;
      _rfidError = null;
    });
    unawaited(_c.rfid.stopInventory());
    try {
      await _c.api.associateRfid(tag, rfidEpc: epc, replace: true);
      _goPutaway();
    } catch (e) {
      setState(() => _rfidError = e is ApiException ? e.message : 'ผูกแท็กไม่สำเร็จ');
    } finally {
      if (mounted) setState(() => _binding = false);
    }
  }

  /// RFID commissioning is optional here (unlike RfidRegisterScreen, whose
  /// whole job is the tag) — a box can go straight from label to putaway
  /// without one and get tagged later from Home's own "ลงทะเบียนแท็ก RFID".
  void _skipRfid() {
    unawaited(_c.rfid.stopInventory());
    _goPutaway();
  }

  void _goPutaway() {
    if (!mounted) return;
    setState(() {
      _step = _Step.putaway;
      _found.clear();
      _selectedEpc = null;
      _locMode = _LocInputMode.scan;
      _locZone = null;
      _locRack = null;
      _locShelf = null;
      _locSlot = null;
      _locScanError = null;
      _locConfirmed = false;
    });
    WidgetsBinding.instance.addPostFrameCallback((_) => _rackScanFocus.requestFocus());
  }

  LocationCascade get _locCascade => LocationCascade(_c.S?.locations ?? const {});

  void _applyRackScan() {
    final raw = _rackScanCtrl.text.trim();
    if (raw.isEmpty) return;
    final loc = _locCascade.resolveBarcode(raw, wh: _c.wh);
    if (loc == null) {
      setState(() => _locScanError = 'ไม่พบรหัสแร็ค "$raw" — ลองกรอกเองด้วยแท็บ "กรอกเอง"');
      _rackScanCtrl.clear();
      return;
    }
    setState(() {
      _locZone = loc.zone.isEmpty ? null : loc.zone;
      _locRack = loc.rack.isEmpty ? null : loc.rack;
      _locShelf = loc.shelf.isEmpty ? null : loc.shelf;
      _locSlot = loc.slot.isEmpty ? null : loc.slot;
      _locScanError = null;
      _locConfirmed = true;
    });
    _rackScanCtrl.clear();
  }

  void _resetLocPicker() {
    setState(() {
      _locConfirmed = false;
      _locScanError = null;
    });
    WidgetsBinding.instance.addPostFrameCallback((_) => _rackScanFocus.requestFocus());
  }

  Future<void> _rescan() async {
    setState(() {
      _found.clear();
      _selectedEpc = null;
      _rfidError = null;
    });
    await _c.rfid.startInventory();
  }

  /// "ข้ามไปก่อน" — same request _submitPutaway already sends when nothing's
  /// picked, just reached without the location cascade blocking the tap.
  /// Clears whatever was partially selected first so a half-picked zone
  /// doesn't get sent alongside three empty fields.
  Future<void> _skipPutaway() async {
    setState(() {
      _locZone = null;
      _locRack = null;
      _locShelf = null;
      _locSlot = null;
    });
    await _submitPutaway();
  }

  Future<void> _submitPutaway() async {
    final tag = _tag;
    if (tag == null || _puttingAway) return;
    if (_c.wh.isEmpty) {
      setState(() => _error = 'เครื่องนี้ยังไม่ได้เลือกคลัง');
      return;
    }
    setState(() {
      _puttingAway = true;
      _error = null;
    });
    try {
      await _c.api.putawayBox(
        tag,
        wh: _c.wh,
        zone: _locZone ?? '',
        rack: _locRack ?? '',
        shelf: _locShelf ?? '',
        slot: _locSlot ?? '',
      );
      final count = _c.prefs.bumpRfidRegisteredToday(_today);
      setState(() => _step = _Step.success);
      _c.toastMsg('รับกล่องเข้าคลังแล้ว', '$tag · วันนี้ $count กล่อง', ResultKind.ok);
      _successTimer?.cancel();
      _successTimer = Timer(const Duration(milliseconds: 1400), _resetForNextBox);
    } catch (e) {
      setState(() => _error = e is ApiException ? e.message : 'จัดเก็บไม่สำเร็จ');
    } finally {
      if (mounted) setState(() => _puttingAway = false);
    }
  }

  String get _today {
    final n = DateTime.now();
    return '${n.year.toString().padLeft(4, '0')}-${n.month.toString().padLeft(2, '0')}-${n.day.toString().padLeft(2, '0')}';
  }

  void _resetForNextBox() {
    if (!mounted) return;
    setState(() {
      _step = _Step.create;
      _tag = null;
      _error = null;
      _rfidError = null;
      _found.clear();
      _selectedEpc = null;
      _locMode = _LocInputMode.scan;
      _locZone = null;
      _locRack = null;
      _locShelf = null;
      _locSlot = null;
      _locScanError = null;
      _locConfirmed = false;
      _typeError = null;
      _tagError = null;
      _tagOverride = false;
      _labelScanError = null;
    });
    _rackScanCtrl.clear();
    _tagCtrl.clear();
    // _selectedType deliberately survives the reset — registering a run of
    // same-type boxes shouldn't require re-picking the type every time.
    _tagCtrl.text = _nextTagForType(_selectedType);
    _labelScanCtrl.clear();
    _lastKeyAt = null;
    _sawBurst = false;
    _tagFocus.requestFocus();
  }

  @override
  Widget build(BuildContext context) {
    final c = context.watch<AppController>();
    final bottom = MediaQuery.of(context).padding.bottom;
    final today = _c.prefs.rfidRegisteredToday(_today);

    // The success card is already-committed work with nothing left to send —
    // let its own timer finish the reset instead of yanking the screen away
    // mid-celebration. Every earlier step still has a pending server call
    // ahead of it, so those redirect the moment the connection drops.
    if (!c.connected && _step != _Step.success && !_leftForOffline) {
      _leftForOffline = true;
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (!mounted) return;
        c.toastMsg('หลุดการเชื่อมต่อ', 'ลงทะเบียนกล่องต้องใช้อินเทอร์เน็ต — กลับหน้าหลักแล้ว', ResultKind.err);
        c.backToHome();
      });
    }

    return Column(
      children: [
        StickyHeader(onBack: c.backToHome, title: const Text('ลงทะเบียนกล่อง')),
        Expanded(
          child: ListView(
            padding: EdgeInsets.fromLTRB(16, 15, 16, bottom + 16),
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('รับเข้าสำเร็จวันนี้', style: TextStyle(fontSize: 13, color: C.muted)),
                  Text('$today กล่อง',
                      style: TextStyle(fontSize: 15, fontWeight: FontWeight.w800, color: C.lime)),
                ],
              ),
              const SizedBox(height: 14),
              _stepper(),
              const SizedBox(height: 14),
              if (_step == _Step.create) _createCard(c),
              if (_step == _Step.label) _labelCard(),
              if (_step == _Step.rfid) _rfidCard(),
              if (_step == _Step.putaway) _putawayCard(c),
              if (_step == _Step.success) _successCard(),
              if (_error != null) ...[
                const SizedBox(height: 10),
                Text(_error!, style: TextStyle(fontSize: 12.5, color: C.red)),
              ],
            ],
          ),
        ),
      ],
    );
  }

  Widget _stepper() {
    final labels = ['สร้าง', 'ติดป้าย', 'RFID', 'Putaway'];
    final idx = switch (_step) {
      _Step.create => 0,
      _Step.label => 1,
      _Step.rfid => 2,
      _Step.putaway => 3,
      _Step.success => 4,
    };
    return Row(
      children: List.generate(labels.length, (i) {
        final done = i < idx;
        final current = i == idx;
        return Expanded(
          child: Row(
            children: [
              Expanded(
                child: Container(
                  height: 4,
                  margin: EdgeInsets.only(left: i == 0 ? 0 : 4, right: i == labels.length - 1 ? 0 : 4),
                  decoration: BoxDecoration(
                    color: done || current ? C.lime : C.neutralBg2,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
            ],
          ),
        );
      }),
    );
  }

  Widget _createCard(AppController c) {
    final types = c.S?.boxtypes.values.whereType<Map>().toList() ?? const [];
    final typeNames = {for (final t in types) (t['id'] ?? '').toString(): '${t['name'] ?? t['id']}'};
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: C.surface,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: C.border2, width: 1.5),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const FieldLabel('ประเภทกล่อง *'),
          AddableDropdown(
            value: _selectedType,
            options: typeNames.keys.toList(),
            labelFor: (id) => typeNames[id] ?? id,
            hint: '— เลือกประเภทกล่อง —',
            nextFocus: _tagOverride ? _tagFocus : null,
            errorText: _typeError,
            onChanged: (v) {
              setState(() {
                _selectedType = v;
                _typeError = null;
              });
              _regenerateTag();
            },
            onAdd: (typed) async {
              final id = typed.toUpperCase().replaceAll(RegExp(r'\s+'), '_');
              try {
                await c.api.createBoxType(id, typed);
                await c.refresh();
                return id;
              } catch (e) {
                if (mounted) {
                  c.toastMsg('เพิ่มประเภทกล่องไม่สำเร็จ', e is ApiException ? e.message : '', ResultKind.err);
                }
                return null;
              }
            },
          ),
          const SizedBox(height: 12),
          FieldLabel('บาร์โค้ดกล่องใหม่ (สร้างอัตโนมัติ) *', error: _tagError),
          if (!_tagOverride)
            // Auto mode: readonly, regenerate + copy + switch-to-manual —
            // mirrors legacy.html's own auto-tag-row exactly.
            Row(
              children: [
                Expanded(
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 13, vertical: 13),
                    decoration: BoxDecoration(
                      color: C.neutralBg,
                      borderRadius: BorderRadius.circular(12),
                      border: _tagError != null ? Border.all(color: C.red, width: 1.5) : null,
                    ),
                    child: Text(_tagCtrl.text,
                        style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w700, fontFamily: 'monospace')),
                  ),
                ),
                const SizedBox(width: 6),
                _iconBtn(Icons.refresh, 'สร้างรหัสใหม่', _regenerateTag),
                const SizedBox(width: 6),
                _iconBtn(Icons.copy_outlined, 'คัดลอก', () {
                  Clipboard.setData(ClipboardData(text: _tagCtrl.text));
                  c.toastMsg('คัดลอกแล้ว', _tagCtrl.text, ResultKind.info);
                }),
              ],
            )
          else
            TextField(
              controller: _tagCtrl,
              focusNode: _tagFocus,
              autofocus: true,
              textCapitalization: TextCapitalization.characters,
              autocorrect: false,
              enableSuggestions: false,
              enabled: !_creating,
              onSubmitted: (_) => _submitCreate(),
              style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w600, fontFamily: 'monospace'),
              decoration: InputDecoration(
                hintText: 'ยิงบาร์โค้ด หรือพิมพ์รหัสเอง',
                hintStyle: TextStyle(fontFamily: 'Roboto', color: C.faint, fontSize: 14),
                isDense: true,
                contentPadding: const EdgeInsets.symmetric(horizontal: 13, vertical: 13),
                filled: true,
                fillColor: C.neutralBg,
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: _tagError != null ? BorderSide(color: C.red, width: 1.5) : BorderSide.none),
                enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                    borderSide: _tagError != null ? BorderSide(color: C.red, width: 1.5) : BorderSide.none),
                // Manual typing has no burst timing to lean on the way a
                // scanner does — this is the explicit "ถัดไป" a slow, one-
                // character-at-a-time typist needs instead of guessing
                // whether the auto-submit timer will ever actually fire.
                suffixIcon: _creating
                    ? const Padding(
                        padding: EdgeInsets.all(12),
                        child: SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)),
                      )
                    : IconButton(
                        icon: const Icon(Icons.arrow_forward),
                        tooltip: 'ถัดไป',
                        onPressed: _submitCreate,
                      ),
              ),
            ),
          const SizedBox(height: 6),
          GestureDetector(
            onTap: _toggleTagOverride,
            child: Row(
              children: [
                Icon(_tagOverride ? Icons.auto_awesome : Icons.edit_outlined, size: 14, color: C.muted),
                const SizedBox(width: 5),
                Text(_tagOverride ? 'ใช้รหัสอัตโนมัติแทน' : 'แก้เอง — ยิงหรือพิมพ์รหัสเอง',
                    style: TextStyle(fontSize: 12, color: C.muted, fontWeight: FontWeight.w600)),
              ],
            ),
          ),
          const SizedBox(height: 8),
          Text('เริ่มจากสร้างข้อมูลกล่อง — ยังไม่ใช่การจ่ายบาร์โค้ดจริง แค่บันทึกว่ากล่องนี้เข้าระบบแล้ว',
              style: TextStyle(fontSize: 11.5, color: C.muted, height: 1.4)),
          const SizedBox(height: 12),
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const FieldLabel('Lot (ไม่บังคับ)'),
                    TextField(
                      controller: _lotCtrl,
                      enabled: !_creating,
                      autocorrect: false,
                      enableSuggestions: false,
                      textCapitalization: TextCapitalization.characters,
                      style: const TextStyle(fontSize: 14, fontFamily: 'monospace'),
                      decoration: pdaInput('ยิงหรือพิมพ์ lot', radius: 12),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: 9),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const FieldLabel('วันหมดอายุ (ไม่บังคับ)'),
                    TextField(
                      controller: _expiryCtrl,
                      enabled: !_creating,
                      autocorrect: false,
                      enableSuggestions: false,
                      style: const TextStyle(fontSize: 14, fontFamily: 'monospace'),
                      decoration: pdaInput('YYYY-MM-DD', radius: 12),
                    ),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 14),
          // Auto mode's barcode field (above) is read-only and already
          // pre-filled the moment a type is picked — _regenerateTag() ran
          // inside the dropdown's own onChanged — so there is nothing left
          // for the operator to type or scan there. Without this button,
          // auto mode had literally no way to move on: the arrow_forward
          // submit icon only exists inside the manual-entry TextField
          // branch above, which auto mode never renders. This button covers
          // both modes — _submitCreate()/_validateCreate() already accept
          // whatever's sitting in _tagCtrl either way.
          PrimaryButton(
            label: 'ถัดไป',
            icon: Icons.arrow_forward,
            trailing: _creating
                ? const SizedBox(
                    width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2))
                : null,
            onTap: (_selectedType == null || _creating) ? null : _submitCreate,
          ),
        ],
      ),
    );
  }

  Widget _labelCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: C.surface,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: C.limeBorder, width: 1.5),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Icon(Icons.check_circle, color: C.limeText, size: 18),
              const SizedBox(width: 8),
              Text('สร้างกล่องแล้ว', style: TextStyle(fontSize: 12.5, fontWeight: FontWeight.w700, color: C.muted)),
            ],
          ),
          const SizedBox(height: 8),
          Text(_tag ?? '',
              style: const TextStyle(fontSize: 26, fontWeight: FontWeight.w800, fontFamily: 'monospace')),
          const SizedBox(height: 14),
          Text('ติดสติกเกอร์บาร์โค้ดที่ตัวกล่องแล้ว ยิงบาร์โค้ดสติกเกอร์นั้นเพื่อยืนยัน',
              style: TextStyle(fontSize: 13, color: C.ink2, fontWeight: FontWeight.w600)),
          const SizedBox(height: 12),
          FieldLabel('ยิงบาร์โค้ดที่ติดแล้ว *', error: _labelScanError),
          TextField(
            controller: _labelScanCtrl,
            focusNode: _labelScanFocus,
            autofocus: true,
            textCapitalization: TextCapitalization.characters,
            autocorrect: false,
            enableSuggestions: false,
            enabled: !_labeling,
            onSubmitted: (_) => _submitLabelScan(),
            style: const TextStyle(fontSize: 18, fontWeight: FontWeight.w600, fontFamily: 'monospace'),
            decoration: InputDecoration(
              hintText: 'ยิงบาร์โค้ดที่ติดบนกล่อง',
              hintStyle: TextStyle(fontFamily: 'Roboto', color: C.faint, fontSize: 14),
              isDense: true,
              contentPadding: const EdgeInsets.symmetric(horizontal: 13, vertical: 13),
              filled: true,
              fillColor: C.neutralBg,
              border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: _labelScanError != null ? BorderSide(color: C.red, width: 1.5) : BorderSide.none),
              enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(12),
                  borderSide: _labelScanError != null ? BorderSide(color: C.red, width: 1.5) : BorderSide.none),
              suffixIcon: _labeling
                  ? const Padding(
                      padding: EdgeInsets.all(12),
                      child: SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2)),
                    )
                  : IconButton(
                      icon: const Icon(Icons.arrow_forward), tooltip: 'ยืนยัน', onPressed: _submitLabelScan),
            ),
          ),
        ],
      ),
    );
  }

  Widget _rfidCard() {
    final connected = _rfidStatus.state == RfidState.connected || !_c.rfid.supported;
    Color dot = _binding ? C.limeText : C.orange;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: C.surface,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: C.orangeBorder, width: 1.5),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              _RfidDot(color: dot, pulsing: !_binding),
              const SizedBox(width: 10),
              Expanded(
                child: Text(_binding ? 'กำลังผูกแท็ก…' : 'ผูกแท็ก RFID (ไม่บังคับ)',
                    style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w700)),
              ),
              if (!_binding)
                TextButton(
                  onPressed: _skipRfid,
                  style: TextButton.styleFrom(padding: EdgeInsets.zero, minimumSize: Size.zero),
                  child: Text('ข้าม', style: TextStyle(fontSize: 12.5, color: C.muted, fontWeight: FontWeight.w700)),
                ),
            ],
          ),
          if (!connected)
            Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Text('เครื่องอ่าน RFID ยังไม่พร้อม — ${_rfidStatus.message.isEmpty ? "กำลังเชื่อมต่อ…" : _rfidStatus.message}',
                  style: TextStyle(fontSize: 12, color: C.orange)),
            ),
          if (_rfidError != null)
            Padding(
              padding: const EdgeInsets.only(top: 8),
              child: Text(_rfidError!, style: TextStyle(fontSize: 12.5, color: C.red)),
            ),
          if (!_binding) ...[
            const SizedBox(height: 12),
            if (_found.isEmpty)
              Text('ยังไม่พบแท็ก — เหนี่ยวไกหรือจ่อแท็กเข้าใกล้เครื่องอ่าน',
                  style: TextStyle(fontSize: 12.5, color: C.faint))
            else ...[
              Row(
                children: [
                  Expanded(
                    child: Text('พบ ${_found.length} แท็ก — เลือกใบที่จะผูก',
                        style: TextStyle(fontSize: 12.5, fontWeight: FontWeight.w700, color: C.muted)),
                  ),
                  GestureDetector(
                    onTap: _rescan,
                    child: Text('ยิงใหม่', style: TextStyle(fontSize: 12.5, color: C.orange)),
                  ),
                ],
              ),
              const SizedBox(height: 6),
              RadioGroup<String>(
                groupValue: _selectedEpc,
                onChanged: (v) => setState(() => _selectedEpc = v),
                child: Column(children: _found.map(_candidateRow).toList()),
              ),
              const SizedBox(height: 10),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: _selectedEpc == null ? null : _bindSelected,
                  style: FilledButton.styleFrom(
                    backgroundColor: C.lime,
                    foregroundColor: C.limeDeep,
                    disabledBackgroundColor: C.neutralBg,
                    disabledForegroundColor: C.faint,
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(13)),
                  ),
                  child: Text(
                    _selectedEpc == null ? 'เลือกแท็กที่จะผูก' : 'ผูกกับ ${_tag ?? ''}',
                    style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800),
                  ),
                ),
              ),
            ],
          ],
        ],
      ),
    );
  }

  Widget _candidateRow(_Candidate c) {
    final selected = _selectedEpc == c.epc;
    return InkWell(
      onTap: () => setState(() => _selectedEpc = c.epc),
      borderRadius: BorderRadius.circular(12),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 6),
        child: Row(
          children: [
            Radio<String>(
              value: c.epc,
              visualDensity: VisualDensity.compact,
              materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
            ),
            const SizedBox(width: 6),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    c.epc,
                    style: TextStyle(
                      fontSize: 13,
                      fontFamily: 'monospace',
                      fontWeight: selected ? FontWeight.w800 : FontWeight.w600,
                      color: selected ? C.ink : C.ink2,
                    ),
                  ),
                  Text('สัญญาณ ${c.rssi ?? '—'} · อ่านได้ ${c.hits} ครั้ง',
                      style: TextStyle(fontSize: 11.5, color: C.faint)),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _putawayCard(AppController c) {
    final cascade = _locCascade;
    final hasLocations = cascade.locations.isNotEmpty;
    final canSubmit = _locZone != null || _locRack != null || _locShelf != null || _locSlot != null;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: C.surface,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: C.border2, width: 1.5),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(_tag ?? '',
              style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w800, fontFamily: 'monospace')),
          const SizedBox(height: 4),
          Text('จัดเก็บที่ ${c.selWhName}', style: TextStyle(fontSize: 12.5, color: C.muted)),
          const SizedBox(height: 14),
          const FieldLabel('วิธีระบุตำแหน่ง'),
          _locModeToggle(),
          const SizedBox(height: 12),
          if (_locMode == _LocInputMode.scan) _locScanArea() else _locManualArea(cascade),
          if (!hasLocations)
            Padding(
              padding: const EdgeInsets.only(top: 10),
              child: Text('ยังไม่มีข้อมูลผังชั้นวาง (Location Master) ในระบบ',
                  style: TextStyle(fontSize: 11.5, color: C.muted)),
            ),
          const SizedBox(height: 14),
          SizedBox(
            width: double.infinity,
            child: FilledButton(
              onPressed: (_puttingAway || !canSubmit) ? null : _submitPutaway,
              style: FilledButton.styleFrom(
                backgroundColor: C.lime,
                foregroundColor: C.limeDeep,
                disabledBackgroundColor: C.neutralBg,
                disabledForegroundColor: C.faint,
                padding: const EdgeInsets.symmetric(vertical: 14),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(13)),
              ),
              child: Text(_puttingAway ? 'กำลังบันทึก…' : 'จัดเก็บขึ้นแร็ค (Putaway)',
                  style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w800)),
            ),
          ),
          const SizedBox(height: 8),
          // Backend's own putaway endpoint already accepts an empty
          // zone/rack/shelf/slot (only `wh` is required) — a box left this
          // way just lands on 'warehouse' with no shelf position yet, the
          // same "รอ Putaway" state the web app's own box list already
          // filters for. This just stops the PDA UI itself from being the
          // thing forcing a location pick that isn't actually required.
          Center(
            child: TextButton(
              onPressed: _puttingAway ? null : _skipPutaway,
              style: TextButton.styleFrom(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6)),
              child: Text('ข้ามไปก่อน — จัดเก็บทีหลัง',
                  style: TextStyle(fontSize: 12.5, color: C.muted, fontWeight: FontWeight.w700)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _locModeToggle() {
    Widget seg(_LocInputMode m, String label, IconData icon) {
      final selected = _locMode == m;
      return Expanded(
        child: GestureDetector(
          onTap: () {
            if (_locMode == m) return;
            setState(() => _locMode = m);
            if (m == _LocInputMode.scan) {
              WidgetsBinding.instance.addPostFrameCallback((_) => _rackScanFocus.requestFocus());
            }
          },
          child: Container(
            padding: const EdgeInsets.symmetric(vertical: 9),
            decoration: BoxDecoration(
              color: selected ? C.ink : Colors.transparent,
              borderRadius: BorderRadius.circular(10),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(icon, size: 15, color: selected ? C.surface : C.ink2),
                const SizedBox(width: 6),
                Text(label,
                    style: TextStyle(
                        fontSize: 12.5,
                        fontWeight: FontWeight.w700,
                        color: selected ? C.surface : C.ink2)),
              ],
            ),
          ),
        ),
      );
    }

    return Container(
      padding: const EdgeInsets.all(3),
      decoration: BoxDecoration(color: C.neutralBg2, borderRadius: BorderRadius.circular(12)),
      child: Row(
        children: [
          seg(_LocInputMode.scan, 'สแกนบาร์โค้ด', Icons.qr_code_scanner),
          seg(_LocInputMode.manual, 'กรอกเอง', Icons.list_alt),
        ],
      ),
    );
  }

  Widget _locScanArea() {
    if (_locConfirmed) {
      final label = [_locZone, _locRack, _locShelf, _locSlot].whereType<String>().join(' · ');
      return Container(
        padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
        decoration: BoxDecoration(
          color: C.limeBg,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(color: C.limeBorder),
        ),
        child: Row(
          children: [
            Icon(Icons.check_circle, size: 18, color: C.limeText),
            const SizedBox(width: 10),
            Expanded(
              child: Text(label,
                  style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w800, fontFamily: 'monospace')),
            ),
            TextButton(
              onPressed: _resetLocPicker,
              style: TextButton.styleFrom(padding: EdgeInsets.zero, minimumSize: Size.zero),
              child: Text('เปลี่ยน', style: TextStyle(fontSize: 12.5, color: C.muted, fontWeight: FontWeight.w700)),
            ),
          ],
        ),
      );
    }
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        TextField(
          controller: _rackScanCtrl,
          focusNode: _rackScanFocus,
          autocorrect: false,
          enableSuggestions: false,
          textCapitalization: TextCapitalization.characters,
          onSubmitted: (_) => _applyRackScan(),
          style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w600, fontFamily: 'monospace'),
          decoration: pdaInput('สแกนบาร์โค้ดป้ายแร็ค เช่น A-R03-2-05', radius: 12).copyWith(
            suffixIcon: IconButton(
              icon: const Icon(Icons.check),
              onPressed: _applyRackScan,
            ),
          ),
        ),
        if (_locScanError != null)
          Padding(
            padding: const EdgeInsets.only(top: 6),
            child: Text(_locScanError!, style: TextStyle(fontSize: 12, color: C.red)),
          ),
      ],
    );
  }

  Widget _locManualArea(LocationCascade cascade) {
    final wh = _c.wh;
    final zones = cascade.zones(wh);
    final racks = cascade.racks(wh, _locZone);
    final shelves = cascade.shelves(wh, _locZone, _locRack);
    final slots = cascade.slots(wh, _locZone, _locRack, _locShelf);

    // A new zone/rack/shelf/slot has to land in the Location Master as a
    // real row (POST /api/masters/locations), not just a free-text value on
    // this one box — otherwise it wouldn't show up as an option anywhere
    // else that reads S.locations. The code is composed from whatever's
    // already picked upstream plus the new value, same shape as the scan
    // barcode format (zone-rack-shelf-slot) this screen already parses.
    Future<String?> addLocationValue(String field, String typed) async {
      final v = typed.toUpperCase();
      final zone = field == 'zone' ? v : _locZone;
      final rack = field == 'rack' ? v : _locRack;
      final shelf = field == 'shelf' ? v : _locShelf;
      final slot = field == 'slot' ? v : _locSlot;
      final code = [zone, rack, shelf, slot].whereType<String>().where((s) => s.isNotEmpty).join('-');
      if (code.isEmpty) return null;
      try {
        await _c.api.createLocation(code: code, wh: wh, zone: zone, rack: rack, shelf: shelf, slot: slot);
        await _c.refresh();
        return v;
      } catch (e) {
        if (mounted) {
          _c.toastMsg('เพิ่มตำแหน่งไม่สำเร็จ', e is ApiException ? e.message : '', ResultKind.err);
        }
        return null;
      }
    }

    String? clampedValue(String? current, List<String> options) =>
        (current != null && options.contains(current)) ? current : null;

    Widget dropdown(String label, String field, String? value, List<String> options,
        void Function(String?) onChanged) {
      return Expanded(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            FieldLabel(label),
            AddableDropdown(
              value: clampedValue(value, options),
              options: options,
              hint: '— ไม่ระบุ —',
              onChanged: onChanged,
              onAdd: (typed) => addLocationValue(field, typed),
            ),
          ],
        ),
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            dropdown('โซน', 'zone', _locZone, zones, (v) {
              setState(() {
                _locZone = v;
                _locRack = null;
                _locShelf = null;
                _locSlot = null;
              });
            }),
            const SizedBox(width: 9),
            dropdown('แร็ค', 'rack', _locRack, racks, (v) {
              setState(() {
                _locRack = v;
                _locShelf = null;
                _locSlot = null;
              });
            }),
          ],
        ),
        const SizedBox(height: 11),
        Row(
          children: [
            dropdown('ชั้น', 'shelf', _locShelf, shelves, (v) {
              setState(() {
                _locShelf = v;
                _locSlot = null;
              });
            }),
            const SizedBox(width: 9),
            dropdown('ช่อง', 'slot', _locSlot, slots, (v) => setState(() => _locSlot = v)),
          ],
        ),
      ],
    );
  }

  Widget _successCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 22),
      decoration: BoxDecoration(color: C.limeBg, borderRadius: BorderRadius.circular(18), border: Border.all(color: C.limeBorder)),
      child: Column(
        children: [
          Text('🎉', style: const TextStyle(fontSize: 32)),
          const SizedBox(height: 8),
          Text('รับกล่อง ${_tag ?? ''} เข้าคลังเรียบร้อยแล้ว',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 14.5, fontWeight: FontWeight.w800, color: C.limeText)),
        ],
      ),
    );
  }
}

/// Small filled/pulsing status dot — same widget RfidRegisterScreen defines
/// for itself; duplicated rather than shared to keep each screen's file
/// self-contained the way this codebase's other single-purpose screens are.
class _RfidDot extends StatelessWidget {
  final Color color;
  final bool pulsing;
  const _RfidDot({required this.color, required this.pulsing});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 14,
      height: 14,
      decoration: BoxDecoration(
        color: color,
        shape: BoxShape.circle,
        boxShadow: pulsing ? [BoxShadow(color: color.withValues(alpha: 0.35), blurRadius: 0, spreadRadius: 4)] : null,
      ),
    );
  }
}
