import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../controllers/app_controller.dart';
import '../services/connect_qr.dart';
import '../services/handheld_profile.dart';
import '../services/i18n.dart';
import '../services/scan_speed_detector.dart';
import '../services/theme_controller.dart';
import '../theme.dart';
import '../widgets/common.dart';

/// Connecting a terminal to the main system — done once, by whoever hands the
/// device out. The operator only points at the server (scan a connect QR or
/// confirm the saved URL). Device-account fields are gone: the app signs in
/// with the credentials already stored on the terminal.
///
/// คลัง/ประตูไม่ได้ถูกถามที่นี่อีกต่อไป — เดิมเคยผูกเครื่องไว้กับประตูเดียวถาวร
/// แต่เครื่องจริงพกไปใช้หลายคลัง/ประตูในกะเดียวกันได้ จึงย้ายไปเลือกตอนกด
/// รับเข้า/ส่งออกจากหน้าแรกแทน (ดู AppController.pickWh/pickGate และ
/// home_screen.dart._pickPostThen)
class DeviceSetupScreen extends StatefulWidget {
  const DeviceSetupScreen({super.key});

  @override
  State<DeviceSetupScreen> createState() => _DeviceSetupScreenState();
}

class _DeviceSetupScreenState extends State<DeviceSetupScreen> {
  late final TextEditingController _url;

  /// Raw keyboard-wedge input, separate from [_url] — a scanned payload is
  /// `BTCFG1:{"url":...}`, not the URL itself, and must be cleared after
  /// every scan or the next scan's characters would land appended to it.
  final TextEditingController _scanBuffer = TextEditingController();
  final FocusNode _urlFocus = FocusNode();
  late final ScanSpeedAutoSubmit _scanDetector;
  String? _scanError;

  /// The one profile this screen actually shows/picks — resolved from what
  /// Android reports the handheld as (see [_detectDevice]), not assumed.
  /// Null while detection is still running.
  HandheldProfile? _profile;

  @override
  void initState() {
    super.initState();
    final c = context.read<AppController>();
    _url = TextEditingController(text: c.prefs.baseUrl);
    _scanDetector = ScanSpeedAutoSubmit(onAutoSubmit: _handleScan);
    _detectDevice(c);
  }

  /// Fires once the barcode gun's keyboard-wedge burst settles — see
  /// [ScanSpeedAutoSubmit]. Parses the `BTCFG1:{...}` payload (see
  /// [ConnectQr], generated by the admin web app's "เชื่อมต่อ PDA" QR) and,
  /// on success, fills [_url] from it. A password in the payload is stored
  /// silently — this screen never asks for a device account. The buffer is
  /// always cleared afterward so the next scan starts clean.
  void _handleScan() {
    final raw = _scanBuffer.text;
    _scanBuffer.clear();
    _scanDetector.reset();
    if (raw.trim().isEmpty) return;
    final parsed = ConnectQr.parse(raw);
    if (parsed == null) {
      setState(() => _scanError =
          'บาร์โค้ดนี้ไม่ใช่บาร์โค้ดเชื่อมต่อระบบ ลองสแกนใหม่อีกครั้ง');
      return;
    }
    final c = context.read<AppController>();
    if (parsed.pass != null) c.prefs.password = parsed.pass!;
    setState(() {
      _scanError = null;
      _url.text = parsed.url;
    });
    // A successful scan supplies everything "ถัดไป" needs — no reason to
    // make the operator tap it separately.
    _connectNow();
  }

  void _connectNow() {
    final c = context.read<AppController>();
    if (c.prefs.deviceModel.isEmpty || c.busy) return;
    c.completeDeviceSetup(baseUrl: _url.text);
  }

  /// Asks Android what this handheld is and applies that through the same
  /// classifier boot uses. An empty report keeps a profile already saved
  /// on the terminal instead of wiping it.
  Future<void> _detectDevice(AppController c) async {
    final info = await c.rfid.deviceInfo();
    final detected = HandheldProfile.classify(
      model: (info['model'] ?? '').toString(),
      manufacturer: (info['manufacturer'] ?? '').toString(),
      brand: (info['brand'] ?? '').toString(),
      androidRelease: (info['androidRelease'] ?? '').toString(),
    );
    if (!mounted) return;
    final shown = detected.modelKnown
        ? detected
        : (HandheldProfile.capabilityFor(c.prefs.deviceModel) ?? detected);
    if (detected.modelKnown) {
      c.applyDetectedHandheld(detected);
    } else if (c.prefs.deviceModel.isEmpty) {
      c.setDeviceModel(shown.id);
    }
    setState(() => _profile = shown);
  }

  @override
  void dispose() {
    _url.dispose();
    _scanBuffer.dispose();
    _urlFocus.dispose();
    _scanDetector.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = context.watch<AppController>();
    final loc = context.watch<LocaleController>();
    final themeCtrl = context.watch<ThemeController>();
    final bottom = MediaQuery.of(context).padding.bottom;
    final canSave = c.prefs.deviceModel.isNotEmpty;
    // Nothing scanned yet this session — "ถัดไป" falls back to offline use
    // instead of trying (and failing) to save an empty server URL.
    final hasScannedUrl = _url.text.trim().isNotEmpty;
    return AutoHideHeader(
      header: StickyHeader(
        onBack: c.backToHome,
        title: Text(loc.t('ตั้งค่าเครื่อง')),
        subtitle:
            Text(loc.t('เชื่อมต่อครั้งเดียว — เลือกคลัง/ประตูตอนเริ่มงานแทน')),
        actions: [
          LangToggleButton(loc: loc),
          const SizedBox(width: 8),
          ThemeToggleButton(ctrl: themeCtrl)
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView(
              padding: EdgeInsets.fromLTRB(16, 18, 16, bottom + 96),
              children: [
                _StepLabel(loc.t('1 · อุปกรณ์ที่ใช้งาน')),
                const SizedBox(height: 11),
                _DeviceModelPicker(
                  profile: _profile,
                  selected: c.prefs.deviceModel,
                  onPick: c.setDeviceModel,
                  loc: loc,
                ),
                const SizedBox(height: 18),
                _StepLabel(loc.t('2 · การเชื่อมต่อระบบหลัก')),
                const SizedBox(height: 11),
                Panel(
                  padding: const EdgeInsets.all(16),
                  radius: 18,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Only shown once there's something to say — connected, or
                      // a real error from the last attempt. Nothing has failed
                      // yet on a fresh setup screen, so there's nothing to report.
                      if (c.connected || c.connError != null) ...[
                        Row(
                          children: [
                            Container(
                              width: 11,
                              height: 11,
                              decoration: BoxDecoration(
                                color: c.connected ? C.lime : C.red,
                                shape: BoxShape.circle,
                              ),
                            ),
                            const SizedBox(width: 11),
                            Expanded(
                              child: Text(
                                c.connected
                                    ? '${loc.t('เชื่อมต่อแล้ว')} · ${c.boxCount} ${loc.t('กล่อง')}'
                                    : c.connError!,
                                style: const TextStyle(
                                    fontSize: 14, fontWeight: FontWeight.w600),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 14),
                      ],
                      FieldLabel(loc.t('ที่อยู่เซิร์ฟเวอร์')),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.symmetric(
                            vertical: 22, horizontal: 14),
                        decoration: BoxDecoration(
                          color: C.neutralBg,
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: C.border2),
                        ),
                        child: Column(
                          children: [
                            Icon(Icons.qr_code_scanner,
                                size: 30, color: C.muted),
                            const SizedBox(height: 10),
                            Text(
                              loc.t('ยิงบาร์โค้ดเพื่อทำการเชื่อมต่อ'),
                              textAlign: TextAlign.center,
                              style: const TextStyle(
                                  fontSize: 14, fontWeight: FontWeight.w700),
                            ),
                            if (_scanError != null) ...[
                              const SizedBox(height: 6),
                              Text(
                                _scanError!,
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                    fontSize: 12,
                                    color: C.red,
                                    fontWeight: FontWeight.w600),
                              ),
                            ] else if (_url.text.isNotEmpty) ...[
                              const SizedBox(height: 6),
                              Text(
                                _url.text,
                                textAlign: TextAlign.center,
                                style: TextStyle(fontSize: 12, color: C.muted),
                              ),
                            ],
                          ],
                        ),
                      ),
                      // Off-screen but focused so the scanner's keyboard-wedge
                      // input lands here — the panel above only ever shows the
                      // resulting message/URL, never a field to type into.
                      // Offstage (not a 0x0 SizedBox) so the TextField still
                      // gets normal layout constraints — a zero-size text
                      // field crashes when this Column's width is recomputed
                      // mid-scroll (e.g. AutoHideHeader collapsing).
                      Offstage(
                        offstage: true,
                        child: TextField(
                          controller: _scanBuffer,
                          focusNode: _urlFocus,
                          autofocus: true,
                          // Keep the hidden wedge target focused for Zebra
                          // scanner input without opening the soft keyboard.
                          keyboardType: TextInputType.none,
                          enableInteractiveSelection: false,
                          showCursor: false,
                          decoration:
                              const InputDecoration.collapsed(hintText: ''),
                          onChanged: (v) {
                            _scanDetector.onChanged(v);
                          },
                          onSubmitted: (_) => _handleScan(),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          Container(
            padding: EdgeInsets.fromLTRB(16, 12, 16, bottom + 14),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.bottomCenter,
                end: Alignment.topCenter,
                colors: [C.bg, const Color(0x00F5F5F7)],
                stops: const [0.68, 1],
              ),
            ),
            child: PrimaryButton(
              label: c.busy
                  ? loc.t('กำลังเชื่อมต่อ…')
                  : hasScannedUrl
                      ? loc.t('บันทึกและเริ่มใช้งาน')
                      : loc.t('ใช้งานแบบ offline'),
              trailing: Icon(Icons.arrow_forward,
                  size: 19, color: canSave ? C.limeDeep : C.faint),
              onTap: (canSave && !c.busy)
                  ? () => hasScannedUrl
                      ? c.completeDeviceSetup(baseUrl: _url.text)
                      : c.useOffline()
                  : null,
            ),
          ),
        ],
      ),
    );
  }
}

/// Step 1 of setup: which handheld this terminal actually is — detected (see
/// [_DeviceSetupScreenState._detectDevice]), not assumed. [profile] is null
/// while that detection is still in flight. Auto-picked once known, so this
/// stays visible as confirmation of what was found rather than a required
/// tap — but it's now confirming a real check, not repeating a hardcoded
/// name at every device that opens this screen.
class _DeviceModelPicker extends StatelessWidget {
  final HandheldProfile? profile;
  final String selected;
  final ValueChanged<String> onPick;
  final LocaleController loc;
  const _DeviceModelPicker({
    required this.profile,
    required this.selected,
    required this.onPick,
    required this.loc,
  });

  @override
  Widget build(BuildContext context) {
    final p = profile;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          loc.t(
              'ระบุรุ่นอุปกรณ์พกพาที่ใช้งานเครื่องนี้ เพื่อให้ระบบตั้งค่าฟังก์ชันเครื่องอ่าน RFID ให้ถูกต้อง'),
          style: TextStyle(fontSize: 12.5, color: C.muted, height: 1.4),
        ),
        const SizedBox(height: 11),
        if (p == null)
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 12),
            child: Center(
                child: SizedBox(
                    width: 22,
                    height: 22,
                    child: CircularProgressIndicator(strokeWidth: 2.4))),
          )
        else ...[
          Padding(
            padding: const EdgeInsets.only(bottom: 9),
            child: _DeviceProfileTile(
              profile: p,
              selected: selected == p.id,
              onTap: () => onPick(p.id),
            ),
          ),
          Text(
            p.hasIntegratedRfid
                ? 'ใช้ Zebra SDK ได้: สแกนบาร์โค้ด, อ่าน/เขียน RFID และค้นหาแท็ก'
                : p.usesZebraSdk
                    ? 'ใช้ Zebra SDK ได้: ${p.barcodeMethod} · RFID ในตัวเครื่องใช้ไม่ได้'
                    : 'อุปกรณ์ Android ทั่วไป: ${p.barcodeMethod} · RFID ใช้ไม่ได้',
            style: TextStyle(fontSize: 11.5, color: C.faint, height: 1.4),
          ),
        ],
      ],
    );
  }
}

class _DeviceProfileTile extends StatelessWidget {
  final HandheldProfile profile;
  final bool selected;
  final VoidCallback onTap;
  const _DeviceProfileTile(
      {required this.profile, required this.selected, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: selected ? C.limeBg : C.surface,
      borderRadius: BorderRadius.circular(16),
      child: InkWell(
        borderRadius: BorderRadius.circular(16),
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 13),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
                color: selected ? C.limeBorder : C.border2,
                width: selected ? 1.5 : 1),
          ),
          child: Row(
            children: [
              Container(
                width: 38,
                height: 38,
                decoration: BoxDecoration(
                  color: selected ? C.lime : C.neutralBg,
                  borderRadius: BorderRadius.circular(11),
                ),
                alignment: Alignment.center,
                child: Icon(
                    profile.hasIntegratedRfid
                        ? Icons.settings_input_antenna
                        : profile.usesZebraSdk
                            ? Icons.qr_code_scanner
                            : Icons.document_scanner_outlined,
                    size: 20,
                    color: selected ? C.limeDeep : C.ink2),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(profile.name,
                        style: const TextStyle(
                            fontSize: 14.5, fontWeight: FontWeight.w700)),
                    const SizedBox(height: 2),
                    Text(
                        [
                          if (profile.androidVersion.isNotEmpty)
                            profile.androidVersion,
                          profile.note
                        ].join(' · '),
                        style: TextStyle(fontSize: 12, color: C.muted)),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              Icon(
                selected ? Icons.check_circle : Icons.radio_button_unchecked,
                size: 22,
                color: selected ? C.limeText : C.chevron,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _StepLabel extends StatelessWidget {
  final String text;
  const _StepLabel(this.text);
  @override
  Widget build(BuildContext context) => Text(text,
      style:
          TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: C.ink));
}
