import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../controllers/app_controller.dart';
import '../services/connect_qr.dart';
import '../services/handheld_capability.dart';
import '../services/i18n.dart';
import '../services/scan_speed_detector.dart';
import '../services/theme_controller.dart';
import '../theme.dart';
import '../widgets/common.dart';
import 'camera_barcode_screen.dart';

/// Connecting a terminal to the main system — done once, by whoever hands the
/// device out. It holds the one password in the whole product — the device's
/// own service account, typed by an admin, never by warehouse staff.
///
/// คลัง/ประตูไม่ได้ถูกถามที่นี่อีกต่อไป — เดิมเคยผูกเครื่องไว้กับประตูเดียวถาวร
/// แต่เครื่องจริงพกไปใช้หลายคลัง/ประตูในกะเดียวกันได้ จึงย้ายไปเลือกตอนกด
/// รับเข้า/ส่งออกจากหน้าแรกแทน (ดู AppController.pickWh/pickGate และ
/// home_screen.dart._pickPostThen)
class DeviceSetupScreen extends StatefulWidget {
  const DeviceSetupScreen({super.key});

  @override
  State<DeviceSetupScreen> createState() => _DeviceSetupScreenState();
}

class _DeviceSetupScreenState extends State<DeviceSetupScreen> {
  late final TextEditingController _url;
  late final TextEditingController _account;
  late final TextEditingController _password;
  /// Raw keyboard-wedge input, separate from [_url] — a scanned payload is
  /// `BTCFG1:{"url":...}`, not the URL itself, and must be cleared after
  /// every scan or the next scan's characters would land appended to it.
  final TextEditingController _scanBuffer = TextEditingController();
  final FocusNode _urlFocus = FocusNode();
  late final ScanSpeedAutoSubmit _scanDetector;
  String? _scanError;
  bool _showAccount = false;

  /// The one profile this screen actually shows/picks — resolved from what
  /// Android reports the handheld as (see [_detectDevice]), not assumed.
  /// Null while detection is still running.
  HandheldCapability? _profile;

  @override
  void initState() {
    super.initState();
    final c = context.read<AppController>();
    _url = TextEditingController(text: c.prefs.baseUrl);
    _account = TextEditingController(text: c.prefs.username);
    _password = TextEditingController();
    _scanDetector = ScanSpeedAutoSubmit(onAutoSubmit: _handleScan);
    _detectDevice(c);
  }

  /// Fires once the barcode gun's keyboard-wedge burst settles — see
  /// [ScanSpeedAutoSubmit]. Parses the `BTCFG1:{...}` payload (see
  /// [ConnectQr], generated by the admin web app's "เชื่อมต่อ PDA" QR) and,
  /// on success, fills [_url]/[_password] from it. The buffer is always
  /// cleared afterward — success or failure — so the next scan starts clean
  /// instead of appending onto whatever's left over.
  void _handleScan() {
    final raw = _scanBuffer.text;
    _scanBuffer.clear();
    _scanDetector.reset();
    if (raw.trim().isEmpty) return;
    final parsed = ConnectQr.parse(raw);
    if (parsed == null) {
      setState(() =>
          _scanError = 'บาร์โค้ดนี้ไม่ใช่บาร์โค้ดเชื่อมต่อระบบ ลองสแกนใหม่อีกครั้ง');
      return;
    }
    setState(() {
      _scanError = null;
      _url.text = parsed.url;
      if (parsed.pass != null) {
        _password.text = parsed.pass!;
        _showAccount = true;
      }
    });
    // A successful scan supplies everything "ถัดไป" needs — no reason to
    // make the operator tap it separately.
    _connectNow();
  }

  void _connectNow() {
    final c = context.read<AppController>();
    if (c.prefs.deviceModel.isEmpty || c.busy) return;
    c.completeDeviceSetup(
      baseUrl: _url.text,
      username: _account.text,
      password: _password.text,
    );
  }

  /// Detect the exact handheld family from Build.MODEL.  A TC52 is also made
  /// by Zebra, but it is a barcode terminal, not an MC3390R with integrated
  /// UHF RFID.  Brand/manufacturer alone must never decide this profile.
  Future<void> _detectDevice(AppController c) async {
    final info = await c.rfid.deviceInfo();
    final resolved = HandheldCapability.fromDeviceInfo(info);
    if (!mounted) return;
    setState(() => _profile = resolved);
    // The profile is a fact reported by Android, not a user preference.  This
    // also migrates a TC52 that an older build incorrectly saved as mc3390r.
    if (c.prefs.deviceModel != resolved.id) c.setDeviceModel(resolved.id);
  }

  Future<void> _scanConnectQrWithCamera() async {
    final raw = await CameraBarcodeScreen.open(
      context,
      title: 'สแกน QR เชื่อมต่อ',
      hint: 'สแกนบาร์โค้ดเชื่อมต่อระบบจากหน้าแอดมิน',
    );
    if (!mounted || raw == null) return;
    _scanBuffer.text = raw;
    _handleScan();
  }

  @override
  void dispose() {
    _url.dispose();
    _account.dispose();
    _password.dispose();
    _scanBuffer.dispose();
    _urlFocus.dispose();
    _scanDetector.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final c = context.watch<AppController>();
    final loc = context.watch<LocaleController>();
    final themeCtrl = context.watch<ThemeController>();
    final bottom = MediaQuery.of(context).padding.bottom;
    final canSave = c.prefs.deviceModel.isNotEmpty;
    // Nothing scanned yet this session — "ถัดไป" falls back to offline use
    // instead of trying (and failing) to save an empty server URL.
    final hasScannedUrl = _url.text.trim().isNotEmpty;
    // A device being provisioned for the first time has nowhere to go back to.
    final canLeave = c.deviceConfigured;

    return AutoHideHeader(
      header: StickyHeader(
        onBack: canLeave ? c.backToHome : null,
        title: Text(loc.t('ตั้งค่าเครื่อง')),
        subtitle:
            Text(loc.t('เชื่อมต่อครั้งเดียว — เลือกคลัง/ประตูตอนเริ่มงานแทน')),
        actions: [
          LangToggleButton(loc: loc),
          const SizedBox(width: 8),
          ThemeToggleButton(ctrl: themeCtrl)
        ],
      ),
      body: Column(
        children: [
          Expanded(
            child: ListView(
              padding: EdgeInsets.fromLTRB(16, 18, 16, bottom + 96),
              children: [
                _StepLabel(loc.t('1 · อุปกรณ์ที่ใช้งาน')),
                const SizedBox(height: 11),
                _DeviceModelPicker(
                  profile: _profile,
                  selected: c.prefs.deviceModel,
                  onPick: c.setDeviceModel,
                  loc: loc,
                ),
                const SizedBox(height: 18),
                _StepLabel(loc.t('2 · การเชื่อมต่อระบบหลัก')),
                const SizedBox(height: 11),
                Panel(
                  padding: const EdgeInsets.all(16),
                  radius: 18,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Only shown once there's something to say — connected, or
                      // a real error from the last attempt. Nothing has failed
                      // yet on a fresh setup screen, so there's nothing to report.
                      if (c.connected || c.connError != null) ...[
                        Row(
                          children: [
                            Container(
                              width: 11,
                              height: 11,
                              decoration: BoxDecoration(
                                color: c.connected ? C.lime : C.red,
                                shape: BoxShape.circle,
                              ),
                            ),
                            const SizedBox(width: 11),
                            Expanded(
                              child: Text(
                                c.connected
                                    ? '${loc.t('เชื่อมต่อแล้ว')} · ${c.boxCount} ${loc.t('กล่อง')}'
                                    : c.connError!,
                                style: const TextStyle(
                                    fontSize: 14, fontWeight: FontWeight.w600),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 14),
                      ],
                      FieldLabel(loc.t('ที่อยู่เซิร์ฟเวอร์')),
                      Container(
                        width: double.infinity,
                        padding: const EdgeInsets.symmetric(
                            vertical: 22, horizontal: 14),
                        decoration: BoxDecoration(
                          color: C.neutralBg,
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(color: C.border2),
                        ),
                        child: Column(
                          children: [
                            Icon(
                                (_profile?.needsCameraBarcode ?? false)
                                    ? Icons.photo_camera_outlined
                                    : Icons.qr_code_scanner,
                                size: 30,
                                color: C.muted),
                            const SizedBox(height: 10),
                            Text(
                              (_profile?.needsCameraBarcode ?? false)
                                  ? loc.t('สแกน QR เชื่อมต่อด้วยกล้อง')
                                  : loc.t('ยิงบาร์โค้ดเพื่อทำการเชื่อมต่อ'),
                              textAlign: TextAlign.center,
                              style: const TextStyle(
                                  fontSize: 14, fontWeight: FontWeight.w700),
                            ),
                            if (_profile?.needsCameraBarcode ?? false) ...[
                              const SizedBox(height: 12),
                              SizedBox(
                                width: double.infinity,
                                child: OutlinedButton.icon(
                                  onPressed: _scanConnectQrWithCamera,
                                  icon: const Icon(Icons.photo_camera_outlined),
                                  label: Text(loc.t('เปิดกล้องสแกน')),
                                ),
                              ),
                            ],
                            if (_scanError != null) ...[
                              const SizedBox(height: 6),
                              Text(
                                _scanError!,
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                    fontSize: 12,
                                    color: C.red,
                                    fontWeight: FontWeight.w600),
                              ),
                            ] else if (_url.text.isNotEmpty) ...[
                              const SizedBox(height: 6),
                              Text(
                                _url.text,
                                textAlign: TextAlign.center,
                                style:
                                    TextStyle(fontSize: 12, color: C.muted),
                              ),
                            ],
                          ],
                        ),
                      ),
                      // Off-screen but focused so the scanner's keyboard-wedge
                      // input lands here — the panel above only ever shows the
                      // resulting message/URL, never a field to type into.
                      // Offstage (not a 0x0 SizedBox) so the TextField still
                      // gets normal layout constraints — a zero-size text
                      // field crashes when this Column's width is recomputed
                      // mid-scroll (e.g. AutoHideHeader collapsing).
                      Offstage(
                        offstage: true,
                        child: TextField(
                          controller: _scanBuffer,
                          focusNode: _urlFocus,
                          autofocus: true,
                          showCursor: false,
                          decoration: const InputDecoration.collapsed(
                              hintText: ''),
                          onChanged: (v) {
                            _scanDetector.onChanged(v);
                          },
                          onSubmitted: (_) => _handleScan(),
                        ),
                      ),
                      const SizedBox(height: 10),
                      // Collapsed by default: on a device that already works,
                      // nobody should be poking at its credentials.
                      GestureDetector(
                        onTap: () =>
                            setState(() => _showAccount = !_showAccount),
                        child: Row(
                          children: [
                            Icon(
                                _showAccount
                                    ? Icons.expand_less
                                    : Icons.expand_more,
                                size: 18,
                                color: C.muted),
                            const SizedBox(width: 4),
                            Text(loc.t('บัญชีประจำเครื่อง'),
                                style: TextStyle(
                                    fontSize: 12.5,
                                    color: C.muted,
                                    fontWeight: FontWeight.w600)),
                          ],
                        ),
                      ),
                      if (_showAccount) ...[
                        const SizedBox(height: 10),
                        TextField(
                          controller: _account,
                          autocorrect: false,
                          decoration:
                              pdaInput(loc.t('ชื่อบัญชีเครื่อง เช่น pda-01')),
                        ),
                        const SizedBox(height: 8),
                        TextField(
                          controller: _password,
                          obscureText: true,
                          decoration: pdaInput(
                              loc.t('รหัสผ่าน (เว้นว่าง = ไม่เปลี่ยน)')),
                        ),
                        const SizedBox(height: 6),
                        Text(
                          loc.t(
                              'บัญชีนี้เป็นของเครื่อง ไม่ใช่ของพนักงาน — ตั้งครั้งเดียวตอนแจกเครื่อง'),
                          style: TextStyle(
                              fontSize: 11.5, color: C.faint, height: 1.4),
                        ),
                      ],
                    ],
                  ),
                ),
              ],
            ),
          ),
          Container(
            padding: EdgeInsets.fromLTRB(16, 12, 16, bottom + 14),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.bottomCenter,
                end: Alignment.topCenter,
                colors: [C.bg, const Color(0x00F5F5F7)],
                stops: const [0.68, 1],
              ),
            ),
            child: PrimaryButton(
              label: c.busy
                  ? loc.t('กำลังเชื่อมต่อ…')
                  : hasScannedUrl
                      ? loc.t('บันทึกและเริ่มใช้งาน')
                      : loc.t('ใช้งานแบบ offline'),
              trailing: Icon(Icons.arrow_forward,
                  size: 19, color: canSave ? C.limeDeep : C.faint),
              onTap: (canSave && !c.busy)
                  ? () => hasScannedUrl
                      ? c.completeDeviceSetup(
                          baseUrl: _url.text,
                          username: _account.text,
                          password: _password.text,
                        )
                      : c.useOffline()
                  : null,
            ),
          ),
        ],
      ),
    );
  }
}

/// Step 1 of setup: which handheld this terminal actually is — detected (see
/// [_DeviceSetupScreenState._detectDevice]), not assumed. [profile] is null
/// while that detection is still in flight.
class _DeviceModelPicker extends StatelessWidget {
  final HandheldCapability? profile;
  final String selected;
  final ValueChanged<String> onPick;
  final LocaleController loc;
  const _DeviceModelPicker({
    required this.profile,
    required this.selected,
    required this.onPick,
    required this.loc,
  });

  @override
  Widget build(BuildContext context) {
    final p = profile;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          loc.t(
              'ระบุรุ่นอุปกรณ์พกพาที่ใช้งานเครื่องนี้ เพื่อให้ระบบตั้งค่าฟังก์ชันเครื่องอ่าน RFID ให้ถูกต้อง'),
          style: TextStyle(fontSize: 12.5, color: C.muted, height: 1.4),
        ),
        const SizedBox(height: 11),
        if (p == null)
          const Padding(
            padding: EdgeInsets.symmetric(vertical: 12),
            child: Center(
                child: SizedBox(
                    width: 22,
                    height: 22,
                    child: CircularProgressIndicator(strokeWidth: 2.4))),
          )
        else ...[
          Padding(
            padding: const EdgeInsets.only(bottom: 9),
            child: _DeviceProfileTile(
              profile: p,
              selected: selected == p.id,
              onTap: () => onPick(p.id),
            ),
          ),
          Text(
            p.hasIntegratedRfid
                ? 'ใช้ Zebra SDK ได้: สแกนบาร์โค้ด, อ่าน/เขียน RFID และค้นหาแท็ก'
                : p.usesZebraSdk
                    ? 'ใช้ Zebra SDK ได้: ${p.barcodeMethod} · RFID ในตัวเครื่องใช้ไม่ได้'
                    : 'SDK บาร์โค้ด/RFID ไม่รองรับรุ่นนี้ · ${p.barcodeMethod}',
            style: TextStyle(fontSize: 11.5, color: C.faint, height: 1.4),
          ),
        ],
      ],
    );
  }
}

class _DeviceProfileTile extends StatelessWidget {
  final HandheldCapability profile;
  final bool selected;
  final VoidCallback onTap;
  const _DeviceProfileTile(
      {required this.profile, required this.selected, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return Material(
      color: selected ? C.limeBg : C.surface,
      borderRadius: BorderRadius.circular(16),
      child: InkWell(
        borderRadius: BorderRadius.circular(16),
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 13),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
                color: selected ? C.limeBorder : C.border2,
                width: selected ? 1.5 : 1),
          ),
          child: Row(
            children: [
              Container(
                width: 38,
                height: 38,
                decoration: BoxDecoration(
                  color: selected ? C.lime : C.neutralBg,
                  borderRadius: BorderRadius.circular(11),
                ),
                alignment: Alignment.center,
                child: Icon(
                    profile.hasIntegratedRfid
                        ? Icons.settings_input_antenna
                        : profile.usesZebraSdk
                            ? Icons.qr_code_scanner
                            : Icons.photo_camera_outlined,
                    size: 20,
                    color: selected ? C.limeDeep : C.ink2),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(profile.displayName,
                        style: const TextStyle(
                            fontSize: 14.5, fontWeight: FontWeight.w700)),
                    const SizedBox(height: 2),
                    Text(
                        [
                          if (profile.androidVersionLabel.isNotEmpty)
                            profile.androidVersionLabel,
                          profile.note
                        ].join(' · '),
                        style: TextStyle(fontSize: 12, color: C.muted)),
                  ],
                ),
              ),
              const SizedBox(width: 8),
              Icon(
                selected ? Icons.check_circle : Icons.radio_button_unchecked,
                size: 22,
                color: selected ? C.limeText : C.chevron,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _StepLabel extends StatelessWidget {
  final String text;
  const _StepLabel(this.text);
  @override
  Widget build(BuildContext context) => Text(text,
      style:
          TextStyle(fontSize: 13, fontWeight: FontWeight.w700, color: C.ink));
}
